export const CREATE_LIST_TASK = 'CREATE_LIST_TASK'
export const SET_LIST_TASK = 'SET_LIST_TASK'

export const SET_SELECTED_LIST = 'SET_SELECTED_LIST'
export const TOGGLE_LIST_TASK = 'TOGGLE_LIST_TASK'